reactive:
  db:
    username: $DB_USERNAME
    password: $DB_PASSWORD
    host: $DB_HOST
    port: 5432
    database: "postgres"
  sandbox:
    akka-sandbox-enabled: false
    rx-java-sandbox-enabled: false
